force-app/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <label>Video Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Video_Comment__c/Video_Comment__c.object-meta.xml
<CustomObject>
    <label>Video Comment</label>
    <nameField>
        <displayFormat>vc-{00000}</displayFormat>
        <label>Video Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Video Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Video_Comment__c/fields/Comment_Body__c.field-meta.xml
<CustomField>
    <fullName>Comment_Body__c</fullName>
    <label>Comment Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video_Comment__c/fields/Time_In_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Seconds__c</fullName>
    <label>Time In Seconds</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Video_Comment__c/fields/Timecode__c.field-meta.xml
<CustomField>
    <fullName>Timecode__c</fullName>
    <label>Timecode</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video_Comment__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <label>Video</label>
    <referenceTo>Video__c</referenceTo>
    <relationshipLabel>Video Comments</relationshipLabel>
    <relationshipName>Video_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/videoComponentController.cls
public with sharing class videoComponentController {
    
    @AuraEnabled(cacheable=true)
    public static List<Video_Comment__c> getVideoComments(string videoID){
        
        List<Video_Comment__c> videoCommentList = [select id, createdBy.Name, comment_body__c, timecode__c, Time_in_seconds__c from video_comment__c where video__c = :videoID order by Time_in_seconds__c asc];
        return videoCommentList;
    }

    @AuraEnabled
    public static List<Video_Comment__c> imperativeVideoComments(string videoID){
        
        List<Video_Comment__c> videoCommentList = [select id, createdBy.Name, comment_body__c, timecode__c, Time_in_seconds__c from video_comment__c where video__c = :videoID order by Time_in_seconds__c asc];
        return videoCommentList;
    }
}